### ISSUE TITLE
Hybrid Quantum Classical CNN to detect Cancer

### ISSUE THREAD

**Issue by contepablod** [lynnlangit/learning-quantum#1]
You can check my HQCCNN to detect cancer in esophagus images.

Now, I am working in a multi labeling  problem with the similar architecture

https://github.com/contepablod/QCNNCancerClassifier

Great Course by the way!

**Comment by lynnlangit** [comment]
Interesting work - I added a link to your notebook (with credit to you) here --> https://github.com/lynnlangit/learning-quantum/blob/main/3_whitepapers/README.md

Thanks for sharing
